---
driver:
  name: vagrant
  customize:
    cpus: 2
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
  attributes:
    wordpress:
      production: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[wordpress-tests::default]
    attributes:
      wordpress:
        creds:
          databag: 'wordpress'
        db:
          name: 'wordpress_test'
          user: 'test_user'
  - name: nginx
    driver:
      network:
        - ["forwarded_port", {guest: 443, host: 8443}]
    run_list:
      - recipe[wordpress-tests::nginx]
    attributes:
      wordpress:
        creds:
          databag: 'wordpress'
        db:
          name: 'wordpress_test'
          user: 'test_user'
        ssl_enabled: true
  - name: php
    driver:
      network:
        - ["forwarded_port", {guest: 443, host: 8443}]
    run_list:
      - recipe[wordpress-tests::php]
    attributes:
      wordpress:
        creds:
          databag: 'wordpress'
        db:
          name: 'wordpress_test'
          user: 'test_user'
        ssl_enabled: true
    exclude:
      ubuntu-14.04
      ubuntu-16.04
